spring.application.name=rate-limiter-service

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2

server.port=${SERVER_PORT:8080}

management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always

# Fixed Window
rate-limiter.fixed-window.max-requests=5
rate-limiter.fixed-window.window-seconds=60

# Sliding Window
rate-limiter.sliding-window.max-requests=5
rate-limiter.sliding-window.window-seconds=60

# Token Bucket
rate-limiter.token-bucket.capacity=10
rate-limiter.token-bucket.refill-rate=1